name: Parse Fail Error
description: Use this tempplate to report when the extension fails to parse your configuration
labels: ["bug"]
assignees:
  Taib-Rabah
body:
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: "User's configuration that causes the error"
  - type: textarea
    id: error
    attributes:
      label: Error
      description: "The error shown"
  - type: input
    id: version
    attributes:
      label: Version
      description: "The extension's version"
