name: Parse Fail
description: Use this template to report a bug where the extension fails to parse the configuration.
title: "[BUG] Failed to parse configuration"
labels: ["bug"]
body:
  - type: textarea
    id: error
    attributes:
      label: Error
      description: The error message shown in the output channel. Please wrap it in a code block for better readability.
      placeholder: "Error message"
      value: "```json\n\n```"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of the extension (also shown in the output channel).
      placeholder: "1.0.0"
    validations:
      required: true
  - type: textarea
    id: anything
    attributes:
      label: Anything else
      description: Anything else you want to add.
      placeholder: "Anything else"
    validations:
      required: false
