name: Parse Fail
description: File a parse fail report.
title: "[BUG]: Failed to parse configuration"
label: ["bug"]
assignees:
  - Taib-Rabah
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Error
      placeholder: Wrap the error within a json codeblock
      description: the error shown in the output chanel
  - type: input
    validations:
      required: true
    attributes:
      label: Version
      validations:
        required: true
      attributes:
        placeholder: ex. 0.1.0
        description: the extension version (also printed in the output chanel)
  - type: textarea
    validations:
      required: false
    attributes:
      label: Anything else
      description: If you have anything else, please tell us.
