name: Parse Fail2
description: Use this template to report a bug where the extension fails to parse the configuration.
title: "[BUG] Failed to parse configuration"
labels: ["bug"]
body:
  - type: textarea
    id: error
    attributes:
      label: Error
      description: The error message that the extension failed to parse the configuration.
      placeholder: "Error message"
    validations:
      required: true
