name: Format
run-name: Format

on: [push]

permissions:
  contents: write

jobs:
  format:
    uses: trdev20-actions/workflows/.github/workflows/format.yml@v1
    with:
      format-script: ci:format
      check-format-script: ci:check-format
      commit-message: Format It
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
